
//Listar todos
GET http://localhost:3000/api/pedidos

###

//Criar pedidos
POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "itens":[
        {
            "produto_id":2,
            "quantidade":3
        }
    ]
}

###

//Deletar pedidos

DELETE http://localhost:3000/api/pedidos/2

###

//Atualizar pedidos
PATCH  http://localhost:3000/api/pedidos/3
Content-Type: application/json

{
    "status": "finalizado"
}

###

//Atualizar todos os dados dos pedidos
PUT http://localhost:3000/api/pedidos/21
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 3
        },
        {
            "produto_id": 2,
            "quantidade": 1
        }
    ]
}

###

//Relatório de faturamento(soma do lucro dos pedidos finalizados)

GET http://localhost:3000/api/pedidos/relatorio