//Listar todos
GET http://localhost:3000/api/produtos

###
//Listar por id
GET http://localhost:3000/api/produtos/3

###
//Cadastrar

POST http://localhost:3000/api/produtos
Content-Type: application/json

{
    "nome":"Cappuccino",
    "preco": "6.00",
    "estoque": 19
}

###
//Atualizar

PATCH http://localhost:3000/api/produtos/3
Content-Type: application/json

{
    "nome": "Café cuado 2"
}

###
//Deletar

DELETE http://localhost:3000/api/produtos/1
